"""Unit tests for platform/puter_native.py.
Generated by MAGNATRIX-OS test generator v0.7.1.
"""
import sys
sys.path.insert(0, "/mnt/agents/MAGNATRIX-OS")

import pytest


def test_imports_without_error():
    """Module must import without syntax/runtime errors."""
    try:
        __import__("platform.puter_native")
    except Exception as e:
        pytest.fail(f"Import failed: {e}")


def test_module_has_classes_or_functions():
    """Module must expose at least one class or function."""
    mod = __import__("platform.puter_native")
    members = [name for name in dir(mod) if not name.startswith("_")]
    assert len(members) > 0, "Module exports nothing"


def test_no_bare_eval_exec():
    """Module must not contain bare eval() or exec() calls."""
    import inspect
    mod = __import__("platform.puter_native")
    source = inspect.getsource(mod)
    # Allow eval in method names and comments, but not bare eval(expression)
    import re
    bare_eval = re.findall(r'\beval\s*\([^)]', source)
    bare_exec = re.findall(r'\bexec\s*\([^)]', source)
    assert len(bare_eval) == 0, f"Found bare eval(): {bare_eval}"
    assert len(bare_exec) == 0, f"Found bare exec(): {bare_exec}"
