#!/usr/bin/env python3
"""
Emergent Goal Formation for MAGNATRIX-OS
========================================
Agent generates its own goals. Curiosity engine, self-directed learning,
goal hierarchy, auto-prioritization. Pure stdlib.

Author: MAGNATRIX-OS Core Infrastructure
License: MIT (Open Source)
"""
from __future__ import annotations
import json, math, random, time
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Callable, Dict, Iterator, List, Optional, Set, Tuple


class GoalStatus(Enum):
    PENDING = "pending"
    ACTIVE = "active"
    COMPLETED = "completed"
    FAILED = "failed"
    ABANDONED = "abandoned"


class GoalType(Enum):
    USER = "user"           # Explicit user request
    DERIVED = "derived"     # Derived from user goal
    EMERGENT = "emergent"   # Self-generated by agent
    CURIOSITY = "curiosity" # Driven by curiosity
    MAINTENANCE = "maintenance"  # System health


@dataclass
class Goal:
    """A goal in the agent's goal hierarchy."""
    goal_id: str
    description: str
    goal_type: GoalType = GoalType.EMERGENT
    status: GoalStatus = GoalStatus.PENDING
    priority: float = 0.5
    parent_id: Optional[str] = None
    sub_goals: List[str] = field(default_factory=list)
    created_at: float = field(default_factory=time.time)
    completed_at: Optional[float] = None
    progress: float = 0.0
    metrics: Dict[str, float] = field(default_factory=dict)
    context: Dict[str, Any] = field(default_factory=dict)
    # Auto-goal specific fields
    novelty_score: float = 0.0
    expected_reward: float = 0.0
    curiosity_value: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d["goal_type"] = self.goal_type.value
        d["status"] = self.status.value
        return d


class CuriosityEngine:
    """Generates curiosity-driven goals."""
    
    def __init__(self, novelty_decay: float = 0.95) -> None:
        self.known_patterns: Dict[str, float] = {}  # pattern -> last_seen_time
        self.novelty_threshold: float = 0.3
        self.novelty_decay = novelty_decay
        self._curiosity_counter = 0
    
    def observe(self, observation: str) -> float:
        """Observe an event and compute novelty."""
        # Extract key patterns
        patterns = self._extract_patterns(observation)
        now = time.time()
        max_novelty = 0.0
        for pattern in patterns:
            if pattern not in self.known_patterns:
                max_novelty = 1.0
            else:
                age = now - self.known_patterns[pattern]
                novelty = math.exp(-age / 3600)  # 1 hour half-life
                max_novelty = max(max_novelty, 1.0 - novelty)
            self.known_patterns[pattern] = now
        return max_novelty
    
    def _extract_patterns(self, text: str) -> List[str]:
        words = re.findall(r'\b[a-zA-Z]{4,}\b', text.lower())
        # Bigrams
        bigrams = [f"{words[i]}_{words[i+1]}" for i in range(len(words)-1)]
        return words[:10] + bigrams[:10]
    
    def generate_curiosity_goals(self, recent_observations: List[str]) -> List[Goal]:
        """Generate goals from high-novelty observations."""
        goals = []
        for obs in recent_observations:
            novelty = self.observe(obs)
            if novelty > self.novelty_threshold:
                self._curiosity_counter += 1
                goals.append(Goal(
                    goal_id=f"curiosity_{self._curiosity_counter}_{int(time.time())}",
                    description=f"Explore: {obs[:100]}",
                    goal_type=GoalType.CURIOSITY,
                    priority=0.3 + novelty * 0.4,
                    curiosity_value=novelty,
                    novelty_score=novelty,
                ))
        return goals
    
    def get_stats(self) -> Dict[str, Any]:
        return {
            "known_patterns": len(self.known_patterns),
            "novelty_threshold": self.novelty_threshold,
        }


class GoalHierarchy:
    """Manages hierarchical goal structure."""
    
    def __init__(self) -> None:
        self.goals: Dict[str, Goal] = {}
        self.root_goals: List[str] = []
    
    def add(self, goal: Goal) -> None:
        self.goals[goal.goal_id] = goal
        if goal.parent_id is None:
            self.root_goals.append(goal.goal_id)
    
    def derive_sub_goals(self, parent_id: str, sub_descriptions: List[str]) -> List[Goal]:
        """Derive sub-goals from a parent goal."""
        parent = self.goals.get(parent_id)
        if not parent:
            return []
        sub_goals = []
        for i, desc in enumerate(sub_descriptions):
            sub = Goal(
                goal_id=f"{parent_id}_sub_{i}",
                description=desc,
                goal_type=GoalType.DERIVED,
                parent_id=parent_id,
                priority=parent.priority * 0.9,
            )
            self.add(sub)
            parent.sub_goals.append(sub.goal_id)
            sub_goals.append(sub)
        return sub_goals
    
    def complete(self, goal_id: str) -> None:
        goal = self.goals.get(goal_id)
        if goal:
            goal.status = GoalStatus.COMPLETED
            goal.completed_at = time.time()
            goal.progress = 1.0
            # Check if parent should be completed
            if goal.parent_id:
                self._check_parent_completion(goal.parent_id)
    
    def _check_parent_completion(self, parent_id: str) -> None:
        parent = self.goals.get(parent_id)
        if not parent or not parent.sub_goals:
            return
        all_done = all(self.goals[g_id].status == GoalStatus.COMPLETED for g_id in parent.sub_goals if g_id in self.goals)
        if all_done:
            parent.status = GoalStatus.COMPLETED
            parent.completed_at = time.time()
            parent.progress = 1.0
    
    def get_active_goals(self) -> List[Goal]:
        return [g for g in self.goals.values() if g.status == GoalStatus.ACTIVE]
    
    def get_hierarchy(self, root_id: Optional[str] = None) -> Dict[str, Any]:
        if root_id:
            goal = self.goals.get(root_id)
            if not goal:
                return {}
            return {
                "goal": goal.to_dict(),
                "sub_goals": [self.get_hierarchy(g_id) for g_id in goal.sub_goals if g_id in self.goals],
            }
        return {gid: self.get_hierarchy(gid) for gid in self.root_goals}
    
    def get_stats(self) -> Dict[str, Any]:
        statuses = {}
        types = {}
        for g in self.goals.values():
            statuses[g.status.value] = statuses.get(g.status.value, 0) + 1
            types[g.goal_type.value] = types.get(g.goal_type.value, 0) + 1
        return {
            "total_goals": len(self.goals),
            "root_goals": len(self.root_goals),
            "by_status": statuses,
            "by_type": types,
        }


class GoalPrioritizer:
    """Automatically prioritizes goals."""
    
    def __init__(self) -> None:
        self.urgency_weights = {"critical": 1.0, "high": 0.7, "normal": 0.4, "low": 0.1}
    
    def compute_priority(self, goal: Goal, context: Dict[str, Any] = None) -> float:
        """Compute dynamic priority for a goal."""
        base = goal.priority
        
        # Age factor: older goals get slight boost
        age_hours = (time.time() - goal.created_at) / 3600
        age_factor = min(1.0 + age_hours * 0.01, 1.5)
        
        # Curiosity bonus
        curiosity_bonus = goal.curiosity_value * 0.2
        
        # Expected reward
        reward_factor = goal.expected_reward * 0.3
        
        # Maintenance penalty (lower priority unless critical)
        type_penalty = 0.7 if goal.goal_type == GoalType.MAINTENANCE else 1.0
        
        priority = (base * age_factor + curiosity_bonus + reward_factor) * type_penalty
        return min(priority, 1.0)
    
    def prioritize(self, goals: List[Goal]) -> List[Goal]:
        """Sort goals by computed priority."""
        scored = [(g, self.compute_priority(g)) for g in goals]
        scored.sort(key=lambda x: x[1], reverse=True)
        return [g for g, _ in scored]


class SelfDirectedLearning:
    """Self-directed learning engine."""
    
    def __init__(self) -> None:
        self.learning_queue: List[Goal] = []
        self.learned_patterns: Dict[str, float] = {}  # pattern -> confidence
        self._learning_counter = 0
    
    def identify_gaps(self, current_capabilities: List[str], desired_capabilities: List[str]) -> List[Goal]:
        """Identify capability gaps and create learning goals."""
        gaps = [c for c in desired_capabilities if c not in current_capabilities]
        goals = []
        for gap in gaps:
            self._learning_counter += 1
            goals.append(Goal(
                goal_id=f"learn_{self._learning_counter}_{int(time.time())}",
                description=f"Learn capability: {gap}",
                goal_type=GoalType.EMERGENT,
                priority=0.6,
                context={"target_capability": gap, "learning_method": "auto"},
            ))
        return goals
    
    def learn_from_feedback(self, action: str, outcome: str, success: bool) -> None:
        """Update learning from action feedback."""
        key = f"{action}->{outcome}"
        if key not in self.learned_patterns:
            self.learned_patterns[key] = 0.5
        if success:
            self.learned_patterns[key] = min(1.0, self.learned_patterns[key] + 0.1)
        else:
            self.learned_patterns[key] = max(0.0, self.learned_patterns[key] - 0.15)
    
    def get_learning_stats(self) -> Dict[str, Any]:
        return {
            "learned_patterns": len(self.learned_patterns),
            "avg_confidence": sum(self.learned_patterns.values()) / len(self.learned_patterns) if self.learned_patterns else 0,
            "queue_size": len(self.learning_queue),
        }


class EmergentGoalFormation:
    """Top-level emergent goal formation engine."""
    
    def __init__(self, agent_id: str = "") -> None:
        self.agent_id = agent_id or f"agent_{int(time.time())}"
        self.curiosity = CuriosityEngine()
        self.hierarchy = GoalHierarchy()
        self.prioritizer = GoalPrioritizer()
        self.learning = SelfDirectedLearning()
        self._goal_counter = 0
    
    def create_goal(self, description: str, goal_type: GoalType = GoalType.USER, priority: float = 0.5, parent_id: Optional[str] = None) -> Goal:
        self._goal_counter += 1
        goal = Goal(
            goal_id=f"goal_{self.agent_id}_{self._goal_counter}",
            description=description,
            goal_type=goal_type,
            priority=priority,
            parent_id=parent_id,
        )
        self.hierarchy.add(goal)
        return goal
    
    def observe(self, observation: str) -> List[Goal]:
        """Observe environment and generate curiosity goals."""
        return self.curiosity.generate_curiosity_goals([observation])
    
    def derive_sub_goals(self, parent_id: str, descriptions: List[str]) -> List[Goal]:
        return self.hierarchy.derive_sub_goals(parent_id, descriptions)
    
    def complete(self, goal_id: str) -> None:
        self.hierarchy.complete(goal_id)
    
    def get_next_goal(self) -> Optional[Goal]:
        active = self.hierarchy.get_active_goals()
        if not active:
            # Promote pending goals
            pending = [g for g in self.hierarchy.goals.values() if g.status == GoalStatus.PENDING]
            if not pending:
                return None
            prioritized = self.prioritizer.prioritize(pending)
            next_goal = prioritized[0]
            next_goal.status = GoalStatus.ACTIVE
            return next_goal
        return self.prioritizer.prioritize(active)[0]
    
    def identify_learning_gaps(self, current: List[str], desired: List[str]) -> List[Goal]:
        return self.learning.identify_gaps(current, desired)
    
    def learn(self, action: str, outcome: str, success: bool) -> None:
        self.learning.learn_from_feedback(action, outcome, success)
    
    def get_stats(self) -> Dict[str, Any]:
        return {
            "agent_id": self.agent_id,
            "hierarchy": self.hierarchy.get_stats(),
            "curiosity": self.curiosity.get_stats(),
            "learning": self.learning.get_learning_stats(),
        }
    
    def to_dict(self) -> Dict[str, Any]:
        return self.get_stats()
