name: Release Automation
on:
  push:
    tags: ['v*']
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: 11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Generate Release Notes
        run: |
          echo "## MAGNATRIX Release ${{ github.ref_name }}" > release_notes.md
          echo "" >> release_notes.md
          git log $(git describe --tags --abbrev=0 HEAD^)..HEAD --oneline >> release_notes.md
      - uses: da05d552573ad5aba039eaac05058a918a7bf631  # v2.2.2
        with:
          body_path: release_notes.md
          files: |
            LICENSE
            README.md
